services:
#  prod_server:
#    build: ./server/
#    container_name: prod_server
#    command: gunicorn --bind 0.0.0.0:5000 'server:main()' # WSGI server
#    expose:
#      - 5000
#    env_file:
#      - ./server/.env
#    restart: always

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - www-html:/var/www/html
      - ./nginx-conf.d:/etc/nginx/conf.d
      - etc-letsencrypt:/etc/letsencrypt
#    depends_on:
#- prod_server

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command: certonly --webroot --webroot-path /var/www/html --email v.zhmurovv@gmail.com --agree-tos --no-eff-email --dry-run -d lixogame.ru -v

volumes:
  www-html:
  etc-letsencrypt: