name: "test"
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SCHEMA: http
      HOST: 127.0.0.1
      PORT: 5000
      URL_PATH: /
      GOOD_USER: user123
      GOOD_PASSWORD: 123
    steps:
      - name: copy repository
        uses: actions/checkout@v4
      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: run server
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          python server/server.py &
          sleep 3
      - name: run is_server_available
        run: python tests/is_server_available.py
      - name: run check_auth
        run: python tests/check_auth.py
      - name: run check_game
        run: python tests/check_game.py