name: "test"
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
#    needs: run-server
    runs-on: ubuntu-latest
    steps:
      - name: copy repository
        uses: actions/checkout@v4
#        with:
#          ref: ${{ env.GITHUB_REF_NAME }}
      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: run test
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          python server/server.py &
          sleep 10
          python client_example.py 127.0.0.1 5000