name: "Deployment prod server"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "*" ]
jobs:
  run-server:
      runs-on: ubuntu-latest
      steps:
        - name: run prod server
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            passphrase: ${{ secrets.PASSPHRASE }}
            script: |
              cd ~/LiXO-server
              git checkout main
              git pull
              sudo docker compose up -d --build
  test:
    needs: run-server
    runs-on: ubuntu-latest
    env:
      SCHEMA: http
      HOST: ${{ secrets.HOST }}
      PORT: 57366
      URL_PATH: /
      GOOD_USER: user123
      GOOD_PASSWORD: 123
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tests
          sparse-checkout-cone-mode: false
      - name: setup-python
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      - name: install requirements
        run: |
          pip install python-dotenv
          pip install requests
      - name: run is_server_available
        run: python tests/is_server_available.py
      - name: run check_auth
        run: python tests/check_auth.py
      - name: run check_game
        run: python tests/check_game.py