name: "ci/cd pipeline"
on:
  push:
    branches: ["ci-cd"]

jobs:
  update-repo:
      runs-on: ubuntu-latest
      steps:
        - name: run dev server
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            passphrase: ${{ secrets.PASSPHRASE }}
            script: |
              cd ~/LiXO-server
              git pull
              sudo docker build -t dev .
              sudo docker run --name dev --rm -d -p 4000:5000 dev
              sleep 10
              python client_example.py
              sleep 15
              sudo docker stop dev