name: "test ssh"
on:
  push:
    branches: ["ci-cd"]

jobs:
  ssh:
      runs-on: ubuntu-latest
      steps:
        - name: multiple command
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            passphrase: ${{ secrets.PASSPHRASE }}            
            script: |
              cd ~/LiXO-server
              git pull
